import type { ElementKey } from "@/types/character";

export const ELEMENT_META: Record<
  ElementKey,
  { en: string; ar: string; icon: string; color: string; glow: string }
> = {
  light:     { en: "Light",     ar: "النور",  icon: "sun",   color: "oklch(0.9 0.14 95)",  glow: "oklch(0.9 0.14 95 / 0.55)" },
  shadow:    { en: "Shadow",    ar: "الظل",   icon: "moon",  color: "oklch(0.68 0.16 275)", glow: "oklch(0.68 0.16 275 / 0.55)" },
  nature:    { en: "Nature",    ar: "الطبيعة", icon: "leaf",  color: "oklch(0.8 0.18 145)", glow: "oklch(0.8 0.18 145 / 0.55)" },
  fire:      { en: "Fire",      ar: "النار",  icon: "flame", color: "oklch(0.72 0.2 40)",  glow: "oklch(0.72 0.2 40 / 0.55)" },
  water:     { en: "Water",     ar: "الماء",  icon: "drop",  color: "oklch(0.78 0.14 225)", glow: "oklch(0.78 0.14 225 / 0.55)" },
  lightning: { en: "Lightning", ar: "البرق",  icon: "bolt",  color: "oklch(0.88 0.17 100)", glow: "oklch(0.88 0.17 100 / 0.55)" },
};

/** Canonical element assignment per character slug. */
export const ELEMENT_BY_SLUG: Record<string, ElementKey> = {
  "ichigo-kurosaki": "fire",
  "rukia-kuchiki": "water",
  "byakuya-kuchiki": "nature",
  "kenpachi-zaraki": "fire",
  "toshiro-hitsugaya": "water",
  "renji-abarai": "fire",
  "uryu-ishida": "light",
  "yoruichi-shihoin": "lightning",
  "kisuke-urahara": "shadow",
  "shunsui-kyoraku": "shadow",
  "grimmjow-jaegerjaquez": "lightning",
  "ulquiorra-cifer": "shadow",
  "hanataro-yamada": "water",
  "ikkaku-madarame": "fire",
  "orihime-inoue": "light",
  "chad-yasutora": "lightning",
  "yhwach": "shadow",
  "aizen-sosuke": "shadow",
  "genryusai-yamamoto": "fire",
  "gin-ichimaru": "shadow",
  "coyote-starrk": "shadow",
  "shinji-hirako": "shadow",
  "lille-barro": "light",
  "askin-nakk-le-vaar": "nature",
  "jugram-haschwalth": "light",
  "shuhei-hisagi": "shadow",
  "oetsu-nimaiya": "water",
  "ichibei-hyosube": "light",
  "kon": "nature",
  "mayuri-kurotsuchi": "shadow",
  "rangiku-matsumoto": "nature",
  "yumichika-ayasegawa": "nature",
  "tite-kubo": "light",
  "ganju-shiba": "nature",
  "don-kanonji": "lightning",
  "senjumaru-shutara": "light",
  "soi-fon": "lightning",
  "baraggan-louisenbairn": "shadow",
  "gerard-valkyrie": "lightning",
  "pernida-parnkgjas": "nature",
  "tokinada-tsunayashiro": "shadow",
  "tier-harribel": "water",
  "sajin-komamura": "fire",
  "izuru-kira": "shadow",
  "soul-king": "light",
  "retsu-unohana": "water",
  "kugo-ginjo": "shadow",
  "shukuro-tsukishima": "shadow",
  "kirio-hikifune": "nature",
  "tenjiro-kirinji": "water",
  "aura-michibane": "shadow",
  "nelliel-tu-odelschwanck": "nature",
  "jushiro-ukitake": "lightning",
  "nanao-ise": "light",
  "azashiro-soya": "shadow",
  "nemu-kurotsuchi": "nature",
  "bambietta-basterbine": "fire",
  "bazz-b": "fire",
  "ikomikidomoe": "fire",
  "kaname-tosen": "shadow",
  "szayelaporro-granz": "nature",
  "qais": "light",
};

export function elementFor(slug: string): ElementKey {
  return ELEMENT_BY_SLUG[slug] ?? "shadow";
}
