/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FollowRouteImport } from './routes/follow'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as IndexRouteImport } from './routes/index'

const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowRoute = FollowRouteImport.update({
  id: '/follow',
  path: '/follow',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/follow': typeof FollowRoute
  '/leaderboard': typeof LeaderboardRoute
  '/quiz': typeof QuizRoute
  '/quotes': typeof QuotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/follow': typeof FollowRoute
  '/leaderboard': typeof LeaderboardRoute
  '/quiz': typeof QuizRoute
  '/quotes': typeof QuotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/follow': typeof FollowRoute
  '/leaderboard': typeof LeaderboardRoute
  '/quiz': typeof QuizRoute
  '/quotes': typeof QuotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/draft' | '/follow' | '/leaderboard' | '/quiz' | '/quotes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/draft' | '/follow' | '/leaderboard' | '/quiz' | '/quotes'
  id:
    | '__root__'
    | '/'
    | '/draft'
    | '/follow'
    | '/leaderboard'
    | '/quiz'
    | '/quotes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraftRoute: typeof DraftRoute
  FollowRoute: typeof FollowRoute
  LeaderboardRoute: typeof LeaderboardRoute
  QuizRoute: typeof QuizRoute
  QuotesRoute: typeof QuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow': {
      id: '/follow'
      path: '/follow'
      fullPath: '/follow'
      preLoaderRoute: typeof FollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraftRoute: DraftRoute,
  FollowRoute: FollowRoute,
  LeaderboardRoute: LeaderboardRoute,
  QuizRoute: QuizRoute,
  QuotesRoute: QuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
