REVOKE ALL ON FUNCTION public.admin_guard() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.am_i_admin() FROM anon;
REVOKE ALL ON FUNCTION public.admin_search_players(text, integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_get_player(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_grant_souls(uuid, integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_grant_xp(uuid, integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_grant_pack(uuid, text, integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_grant_character(uuid, text, integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_grant_item(uuid, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_unlock_achievement(uuid, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_set_streak(uuid, integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_transfer_progress(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.am_i_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_search_players(text, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_player(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_grant_souls(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_grant_xp(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_grant_pack(uuid, text, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_grant_character(uuid, text, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_grant_item(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_unlock_achievement(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_streak(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_transfer_progress(uuid, uuid) TO authenticated;